/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
package pl.jwizard.jwc.core.util.ext

import net.dv8tion.jda.api.entities.channel.Channel
import pl.jwizard.jwc.core.util.formatQualifier

/**
 * Extension property for the [Channel] class that formats and retrieves a "qualifier" string. The qualifier is
 * generated by combining the channel's name and its unique ID (as a long) in a formatted string.
 *
 * @receiver Channel The channel instance for which the qualifier is being retrieved.
 * @return A formatted string containing the channel's name and ID.
 * @author Miłosz Gilga
 */
val Channel.qualifier get() = formatQualifier(name, idLong)
