#!/bin/bash

#
# Copyright (c) 2023 by MILOSZ GILGA <http://miloszgilga.pl>
#
# File name: lang-gen.sh
# Last modified: 31/03/2023, 14:07
# Project name: jwizard-discord-bot
#
# Licensed under the MIT license; you may not use this file except in compliance with the License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN ALL COPIES OR
# SUBSTANTIAL PORTIONS OF THE SOFTWARE.
#
# The software is provided "as is", without warranty of any kind, express or implied, including but not limited
# to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event
# shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an
# action of contract, tort or otherwise, arising from, out of or in connection with the software or the use
# or other dealings in the software.
#

RELATIVE_TO_LANG_DIR="lang"
SAMPLE_LANG_FILE_NAME="messages_en_us.properties"
ARG_KEY="--lang"

IS_ARG_NOT_EXIST=false

if [ "$#" -eq 0 ]; then
    IS_ARG_NOT_EXIST=true
fi

IFS="=" read -r key value <<< "$@"
if [ "$key" == $ARG_KEY ]; then
    OUTPUT_FILE_NAME="messages_$value.properties"
else
    IS_ARG_NOT_EXIST=true
fi

if [ $IS_ARG_NOT_EXIST == true ]; then
    echo "[bash gen script err] <> Available only argument: --lang=<i18n tag>"
    exit 1
fi

if ! cd $RELATIVE_TO_LANG_DIR; then
    echo "[bash gen script err] <> Directory /lang not exist in ROOT project context"
    exit 2
fi

if [ ! -f "$SAMPLE_LANG_FILE_NAME" ]; then
    echo "[bash gen script err] <> Sample file '$SAMPLE_LANG_FILE_NAME' not exist in lang directory"
    exit 3
fi

if [ -f "$OUTPUT_FILE_NAME" ]; then
    echo "[bash gen script err] <> Lang file '$OUTPUT_FILE_NAME' already exist in lang directory"
    exit 4
fi

touch "$OUTPUT_FILE_NAME"
{
    echo "# Generated by: ${0##*/}, $(date +"%D %T")";
    echo "# Bash interpreter version: ${BASH_VERSION}";
    echo
    echo -n "# $OUTPUT_FILE_NAME"
} >> "$OUTPUT_FILE_NAME"

while IFS= read -r line
do
    if [[ $line =~ ^#.* ]]; then
        continue
    fi
    IFS="=" read -r key value <<< "$line"
    if [ -z "$line" ]; then
        echo "$key" >> "$OUTPUT_FILE_NAME"
    else
        echo "$key=" >> "$OUTPUT_FILE_NAME"
    fi
done < "$SAMPLE_LANG_FILE_NAME"

echo "[bash gen script info] <> Output lang file '$OUTPUT_FILE_NAME' was successfully generated"
