#!/bin/bash

#
# Copyright (c) 2023 by MILOSZ GILGA <http://miloszgilga.pl>
#
# File name: lang-gen.sh
# Last modified: 02/04/2023, 15:45
# Project name: jwizard-discord-bot
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     <http://www.apache.org/license/LICENSE-2.0>
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the license.
#

RELATIVE_TO_LANG_DIR="lang"
SAMPLE_LANG_FILE_NAME="messages_en_us.properties"
ARG_KEY="--lang"

IS_ARG_NOT_EXIST=false

if [ "$#" -eq 0 ]; then
    IS_ARG_NOT_EXIST=true
fi

IFS="=" read -r key value <<< "$@"
if [ "$key" == $ARG_KEY ]; then
    OUTPUT_FILE_NAME="messages_$value.properties"
else
    IS_ARG_NOT_EXIST=true
fi

if [ $IS_ARG_NOT_EXIST == true ]; then
    echo "[bash gen script err] <> Available only argument: --lang=<i18n tag>"
    exit 1
fi

if ! cd $RELATIVE_TO_LANG_DIR; then
    echo "[bash gen script err] <> Directory /lang not exist in ROOT project context"
    exit 2
fi

if [ ! -f "$SAMPLE_LANG_FILE_NAME" ]; then
    echo "[bash gen script err] <> Sample file '$SAMPLE_LANG_FILE_NAME' not exist in lang directory"
    exit 3
fi

if [ -f "$OUTPUT_FILE_NAME" ]; then
    echo "[bash gen script err] <> Lang file '$OUTPUT_FILE_NAME' already exist in lang directory"
    exit 4
fi

touch "$OUTPUT_FILE_NAME"
{
    echo "# Generated by: ${0##*/}, $(date +"%D %T")";
    echo "# Bash interpreter version: ${BASH_VERSION}";
    echo
    echo -n "# $OUTPUT_FILE_NAME"
} >> "$OUTPUT_FILE_NAME"

while IFS= read -r line
do
    if [[ $line =~ ^#.* ]]; then
        continue
    fi
    IFS="=" read -r key value <<< "$line"
    if [ -z "$line" ]; then
        echo "$key" >> "$OUTPUT_FILE_NAME"
    else
        echo "$key=" >> "$OUTPUT_FILE_NAME"
    fi
done < "$SAMPLE_LANG_FILE_NAME"

echo "[bash gen script info] <> Output lang file '$OUTPUT_FILE_NAME' was successfully generated"
