#
#  Copyright (c) 2023 by MILOSZ GILGA <http://miloszgilga.pl>
#
#  File name: lang-gen.py
#  Last modified: 02/04/2023, 15:45
#  Project name: jwizard-discord-bot
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
#  file except in compliance with the License. You may obtain a copy of the License at
#
#      <http://www.apache.org/license/LICENSE-2.0>
#
#  Unless required by applicable law or agreed to in writing, software distributed under
#  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
#  OF ANY KIND, either express or implied. See the License for the specific language
#  governing permissions and limitations under the license.
#

import sys
import os.path
import platform
from datetime import datetime

relative_to_lang_dir = 'lang'
sample_lang_file_name = 'messages_en_us.properties'
arg_key = '--lang'

sys.argv.pop(0)
is_arg_not_exist = False

if len(sys.argv) != 1:
    is_arg_not_exist = True

i18n_tag_key_value = sys.argv[0].split('=')
if i18n_tag_key_value[0] != arg_key:
    is_arg_not_exist = True

if is_arg_not_exist:
    print('[python gen script err] <> Available only argument: --lang=<i18n tag>')
    exit(1)

output_file_name = 'messages_' + i18n_tag_key_value[1] + '.properties'

path_parent = os.path.dirname(os.getcwd())
os.chdir(path_parent)
abs_lang_file_path = os.path.join(os.getcwd(), sample_lang_file_name)
abs_output_lang_file_path = os.path.join(os.getcwd(), output_file_name)

if not os.path.exists(abs_lang_file_path) and not os.path.isfile(abs_lang_file_path):
    print(f'[python gen script err] <> Sample file \'{sample_lang_file_name}\' not exist in lang directory')
    exit(2)

if os.path.isfile(abs_output_lang_file_path) and os.path.exists(abs_output_lang_file_path):
    print(f'[python gen script err] <> Lang file \'{output_file_name}\' already exist in lang directory')
    exit(3)

sample_lang_file = open(abs_lang_file_path, 'r')
output_lang_file = open(abs_output_lang_file_path, 'a')

dt_string = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
output_lang_file.write(f'# Generated by: {os.path.basename(__file__)}, {dt_string}\n')
output_lang_file.write(f'# Python interpreter version: {platform.python_version()}\n\n')
output_lang_file.write(f'# {output_file_name}')

with sample_lang_file as f:
    for line in f:
        if line.startswith('#'):
            continue
        if line.strip():
            key_data = line.split('=')[0] + "="
            output_lang_file.write(f'{key_data}\n')
        else:
            output_lang_file.write('\n')

print(f'[python gen script info] <> Output lang file \'{output_file_name}\' was successfully generated')

sample_lang_file.close()
output_lang_file.close()
